services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.14
    container_name: paperless
    environment:
      - USERMAP_UID=0
      - USERMAP_GID=0
      - PAPERLESS_TIME_ZONE=Europe/Prague
      - PAPERLESS_URL=https://paperless.home.pupca.cz
      - PAPERLESS_REDIS=redis://:${REDIS_PASS}@redis:6379
      - PAPERLESS_DBHOST=postgres
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=${PAPERLESS_POSTGRES_PASS}
    volumes:
      - ../../data/paperless/consume:/usr/src/paperless/consume
      - ../../data/paperless/data:/usr/src/paperless/data
      - ../../data/paperless/export:/usr/src/paperless/export
      - ${MEDIA_ROOT}/documents:/usr/src/paperless/media
    ports:
      - "8001:8000/tcp"
    networks: [homelab]
    restart: unless-stopped
