include:
  - media/compose.yml
  - home/compose.yml
  - postgres/compose.yml
  - redis/compose.yml
  - influxdb/compose.yml
  - paperless/compose.yml
  - vaultwarden/compose.yml
  - wud/compose.yml
  - door_opener/compose.yml
  - monitoring/compose.yml
