services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=homeassistant
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - TZ=Europe/Prague
    volumes:
      - ../../data/influxdb/data:/var/lib/influxdb2
      - ../../data/influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086/tcp"
    networks: [homelab]
    restart: unless-stopped
